line-length = 100

[lint]
select = ["ALL"]  # Enable all rules
ignore = [
	"ANN401",
	"COM812",
	"D",
	"ERA001",
	"N815",
	"N803",
	"PLR2004",
	"PTH",
	"RET502",
	"RET504",
	"S101",
]

[lint.flake8-tidy-imports]
banned-module-level-imports = [
    "apps",
]
